# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNKhipu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNKhipu
  pod 'khenshin', :git => 'https://github.com/khipu/khenshin-pod.git', :tag => '1.611'

end
